# Wokwi local firmware configuration
[wokwi]
version = 1
# Use the locally built ELF from PlatformIO to skip cloud build queues
firmware = "../.pio/build/esp32dev/firmware.elf"
elf = "../.pio/build/esp32dev/firmware.elf"
